name: Deploy Docusaurus site to GitHub Pages

# Re-deploy every time main is updated
on:
  push:
    branches: [main]

# Top-level permissions so the build job can push Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # ------- 1) Build the static site ---------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout source
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # install deps & build Docusaurus
      - run: npm ci
      - run: npm run build          # → creates ./build

      # upload the ./build folder as a Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build               # <-- do NOT change

  # ------- 2) Publish that artifact to Pages ------------------------
  deploy:
    needs: build                    # wait for build job
    runs-on: ubuntu-latest

    # GitHub expects this EXACT environment stanza
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # this job specifically needs the Pages perms
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

