name: Deploy Docusaurus to Pages

on:
  push:
    branches: [main]

permissions:                      # 👈 let the action push the site
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run build          # → creates ./build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build               # 👈 what we just built

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # --- NEW: prepare the environment -------------------------------
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      # --- deploy ----------------------------------------------------
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
